# Generated by Django 3.0.2 on 2020-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closeprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('stockdate', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True)),
            ],
            options={
                'db_table': 'closeprices',
                'managed': False,
            },
        ),
    ]
