# Generated by Django 3.0.2 on 2020-06-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbollist',
            fields=[
                ('tiker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('companyname', models.TextField()),
                ('etf', models.BooleanField()),
                ('financial_status', models.CharField(max_length=20)),
                ('nasdaq_symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'symbollist',
                'managed': False,
            },
        ),
    ]
