# Generated by Django 3.0.2 on 2020-06-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_symbollist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbollist',
            options={},
        ),
    ]
