# Generated by Django 3.0.2 on 2020-06-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20200602_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbollist',
            options={'managed': False},
        ),
    ]
